---
title: "Class 05: Data exploration and visualization in R"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# class 5 R graphics and plots
weight <- read.table("bimm143_05_rstats/weight_chart.txt", header = TRUE)

```

```{r}
# plot a scaterplot of age vs weight
plot(weight$Age, weight$Weight, xlab="Age (M)", ylab="Weight (kg)",pch=18, cex=(2),col="red")
```

```{r}
#Class05 Section 2B Barplot

feature_counts <- read.table("bimm143_05_rstats/feature_counts.txt", header = TRUE, sep="\t")
feature_counts
par(mar=c(5,12,1,4))
barplot(feature_counts$Count,names.arg = feature_counts$Feature, horiz = TRUE, xlab = "counts", las = 1, xlim = c(0,80000))
```

```{r}
genes <- read.table("bimm143_05_rstats/up_down_expression.txt", header = TRUE, sep="\t")

palette()
levels(genes$State)
nrow(genes)
ncol(genes)
unique(genes$State)
table(genes$State)
palette(c("blue","grey","red"))
par(mar=c(5.1,11.5,4.1,11.1))
plot(genes$Condition1, genes$Condition2, col=genes$State, xlab = "Condition #1", ylab = "Condition #2", main = "Generic Title", xlim = (c(-5,15)), ylim = (c(-5,15)))
```

